
name: Create release
on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version Eg: 1.6.9'

jobs:
  build-linux-64:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go mod tidy
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: ./make

      - uses: AppImageCrafters/build-appimage-action@master
        with:
          recipe: 'AppImage-Builder.yml'
        env:
          BREAD_VERSION: ${{github.event.inputs.version}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'bread_linux_binary'
          path: './bread-${{github.event.inputs.version}}-x86_64.AppImage'

  create-release:
    needs: [build-linux-64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Clean previous binaries
      run: ./make clean
        
    - name: Download Linux build artifacts 
      uses: actions/download-artifact@v2
      with:
        name: bread_linux_binary
        path: ./bread-${{github.event.inputs.version}}-x86_64.AppImage

    - name: Send Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Bread v${{github.event.inputs.version}} has Been built sucessfully'
